---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: vraj-naik
  gather_facts: no
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "naikvraj/devops-integration"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator naikvraj/devops-integration

    
    - name: Disable host key checking
      ansible.builtin.set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
